import gsap from "gsap";
import MotionPathPlugin from "gsap/MotionPathPlugin";
gsap.registerPlugin(MotionPathPlugin);

const SVG_NS="http://www.w3.org/2000/svg", DEFAULT_SVG_WIDTH=900, DEFAULT_SVG_HEIGHT=500, HANDLE_SCREEN_RADIUS=7;
const svg=document.getElementById("svg"), stage=document.querySelector(".stage"), curve=document.getElementById("curve"), output=document.getElementById("output"), box=document.getElementById("box");
const backgroundImage=document.getElementById("backgroundImage"), backgroundUpload=document.getElementById("backgroundUpload"), clearBackground=document.getElementById("clearBackground"), toggleBackground=document.getElementById("toggleBackground"), toggleImageDragging=document.getElementById("toggleImageDragging"), backgroundStatus=document.getElementById("backgroundStatus"), backgroundOpacity=document.getElementById("backgroundOpacity"), backgroundMode=document.getElementById("backgroundMode"), scalePathOnUpload=document.getElementById("scalePathOnUpload"), canvasSize=document.getElementById("canvasSize"), pointsTableBody=document.getElementById("pointsTableBody");
const startX=document.getElementById("startX"), startY=document.getElementById("startY"), endX=document.getElementById("endX"), endY=document.getElementById("endY");
let snap=false, lockEndpoints=false, active=null, backgroundUrl=null, backgroundFileName="", backgroundDrag=null, imageDraggingEnabled=false;
const grid=20, backgroundSettings={visible:true,opacity:1,mode:"fit",x:0,y:0};
let points=[{x:79,y:117},{x:250,y:50},{x:450,y:50},{x:625,y:175}];
function clamp(v,min,max){return Math.min(Math.max(v,min),max)}
function getCanvasSize(){return{width:svg.viewBox.baseVal.width||DEFAULT_SVG_WIDTH,height:svg.viewBox.baseVal.height||DEFAULT_SVG_HEIGHT}}
function getHandleRadius(){const {width}=getCanvasSize(),rect=svg.getBoundingClientRect(),scale=rect.width?rect.width/width:1;return HANDLE_SCREEN_RADIUS/scale}
function updateCanvasInfo(){const {width,height}=getCanvasSize();canvasSize.textContent=`${Math.round(width)} × ${Math.round(height)} px`}
function setSvgCanvasSize(w,h){svg.setAttribute("width",w);svg.setAttribute("height",h);svg.setAttribute("viewBox",`0 0 ${w} ${h}`);stage.style.setProperty("--canvas-width",`${w}px`);backgroundImage.setAttribute("width",w);backgroundImage.setAttribute("height",h);updateCanvasInfo()}
function resetToDefaultCanvas(){setSvgCanvasSize(DEFAULT_SVG_WIDTH,DEFAULT_SVG_HEIGHT);backgroundSettings.x=backgroundSettings.y=0}
function scalePath(fw,fh,tw,th){if(!scalePathOnUpload.checked||!fw||!fh)return;const sx=tw/fw,sy=th/fh;points=points.map(p=>({x:p.x*sx,y:p.y*sy}))}
function updateEndpointInputs(){const s=points[0],e=points[points.length-1];startX.value=Math.round(s.x);startY.value=Math.round(s.y);endX.value=Math.round(e.x);endY.value=Math.round(e.y)}
function updateBackgroundControls(){const has=Boolean(backgroundUrl);clearBackground.disabled=!has;toggleBackground.disabled=!has;toggleImageDragging.disabled=!has;backgroundOpacity.disabled=!has;backgroundMode.disabled=!has;backgroundOpacity.value=String(backgroundSettings.opacity);backgroundMode.value=backgroundSettings.mode;toggleBackground.textContent=backgroundSettings.visible?"Hide":"Show";toggleImageDragging.textContent=`Move Image: ${imageDraggingEnabled?"ON":"OFF"}`;backgroundStatus.textContent=has?backgroundFileName:"No image selected"}
function updateBackgroundVisuals(){if(!backgroundUrl){backgroundImage.setAttribute("visibility","hidden");return}const {width,height}=getCanvasSize();backgroundImage.setAttribute("href",backgroundUrl);backgroundImage.setAttribute("visibility",backgroundSettings.visible?"visible":"hidden");backgroundImage.setAttribute("opacity",backgroundSettings.opacity);backgroundImage.setAttribute("preserveAspectRatio",backgroundSettings.mode==="cover"?"xMidYMid slice":"xMidYMid meet");backgroundImage.setAttribute("width",width);backgroundImage.setAttribute("height",height);backgroundImage.setAttribute("x",backgroundSettings.x);backgroundImage.setAttribute("y",backgroundSettings.y);backgroundImage.style.cursor=imageDraggingEnabled?"grab":"default"}
function buildPath(){let d=`M ${points[0].x.toFixed(2)} ${points[0].y.toFixed(2)}`;for(let i=1;i<points.length;i+=3){const a=points[i],b=points[i+1],c=points[i+2];if(!c)break;d+=` C ${a.x.toFixed(2)} ${a.y.toFixed(2)}, ${b.x.toFixed(2)} ${b.y.toFixed(2)}, ${c.x.toFixed(2)} ${c.y.toFixed(2)}`}return d}
function pointType(i){if(i===0)return"Start";if(i===points.length-1)return"End";return i%3===1?"Control 1":"Control 2"}
function renderPointsTable(){pointsTableBody.innerHTML="";points.forEach((p,i)=>{const row=document.createElement("tr");row.innerHTML=`<td>${i}</td><td>${pointType(i)}</td><td><input type="number" step="0.01" data-point-index="${i}" data-axis="x" value="${p.x.toFixed(2)}" aria-label="Point ${i} X"></td><td><input type="number" step="0.01" data-point-index="${i}" data-axis="y" value="${p.y.toFixed(2)}" aria-label="Point ${i} Y"></td>`;pointsTableBody.appendChild(row)})}
function update(){const path=buildPath(),r=getHandleRadius();curve.setAttribute("d",path);output.textContent=path;svg.querySelectorAll("circle").forEach(c=>c.remove());points.forEach((p,i)=>{const c=document.createElementNS(SVG_NS,"circle");c.setAttribute("cx",p.x);c.setAttribute("cy",p.y);c.setAttribute("r",r);c.setAttribute("fill",i%3===0?"#4f9dff":"#4fd18b");c.dataset.index=i;svg.appendChild(c)});renderPointsTable()}
function toSvgCoords(e){const rect=svg.getBoundingClientRect(),{width,height}=getCanvasSize();return{x:(e.clientX-rect.left)*(width/rect.width||1),y:(e.clientY-rect.top)*(height/rect.height||1)}}
function onPointerDown(e){if(e.target===backgroundImage&&backgroundUrl&&backgroundSettings.visible&&imageDraggingEnabled){const p=toSvgCoords(e);backgroundDrag={offsetX:p.x-backgroundSettings.x,offsetY:p.y-backgroundSettings.y};return}if(e.target.tagName!=="circle")return;const i=Number(e.target.dataset.index);if(lockEndpoints&&(i===0||i===points.length-1))return;active=i}
function onPointerMove(e){if(backgroundDrag){const p=toSvgCoords(e),{width,height}=getCanvasSize();backgroundSettings.x=clamp(p.x-backgroundDrag.offsetX,-width,width);backgroundSettings.y=clamp(p.y-backgroundDrag.offsetY,-height,height);updateBackgroundVisuals();return}if(active===null)return;let{x,y}=toSvgCoords(e);if(snap){x=Math.round(x/grid)*grid;y=Math.round(y/grid)*grid}points[active]={x:clamp(x,0,getCanvasSize().width),y:clamp(y,0,getCanvasSize().height)};updateEndpointInputs();update()}
function onPointerUp(){backgroundDrag=null;active=null}
function addSegment(){const {width,height}=getCanvasSize(),last=points[points.length-1],margin=getHandleRadius(),clampX=v=>clamp(v,margin,width-margin),clampY=v=>clamp(v,margin,height-margin);const next=[{x:clampX(last.x+100),y:clampY(last.y-150)},{x:clampX(last.x+200),y:clampY(last.y+150)},{x:clampX(last.x+300),y:clampY(last.y)}];points.push(...next);updateEndpointInputs();update()}
function removeSegment(){if(points.length<=4)return;points.splice(-3,3);updateEndpointInputs();update()}
function toggleSnap(e){snap=!snap;e.currentTarget.textContent=`Snap: ${snap?"ON":"OFF"}`}
function toggleLockEndpoints(e){lockEndpoints=!lockEndpoints;e.currentTarget.textContent=`Lock Endpoints: ${lockEndpoints?"ON":"OFF"}`}
function toggleImageDraggingMode(){imageDraggingEnabled=!imageDraggingEnabled;backgroundDrag=null;updateBackgroundControls();updateBackgroundVisuals()}
function applyEndpoints(){points[0]={x:clamp(Number(startX.value),0,getCanvasSize().width),y:clamp(Number(startY.value),0,getCanvasSize().height)};points[points.length-1]={x:clamp(Number(endX.value),0,getCanvasSize().width),y:clamp(Number(endY.value),0,getCanvasSize().height)};update()}
function swapStartEnd(){const rev=[points[points.length-1]];for(let i=points.length-2;i>=1;i-=3)rev.push(points[i],points[i-1],points[i-2]);points=rev;updateEndpointInputs();update()}
function handleBackgroundUpload(e){const[file]=e.target.files;if(!file)return;if(backgroundUrl)URL.revokeObjectURL(backgroundUrl);const{width:ow,height:oh}=getCanvasSize();backgroundUrl=URL.createObjectURL(file);backgroundFileName=file.name;backgroundSettings.visible=true;backgroundSettings.opacity=Number(backgroundOpacity.value)||1;backgroundSettings.x=backgroundSettings.y=0;imageDraggingEnabled=false;backgroundDrag=null;const image=new Image();image.onload=()=>{const w=image.naturalWidth||DEFAULT_SVG_WIDTH,h=image.naturalHeight||DEFAULT_SVG_HEIGHT;scalePath(ow,oh,w,h);setSvgCanvasSize(w,h);updateEndpointInputs();updateBackgroundVisuals();updateBackgroundControls();update()};image.src=backgroundUrl}
function removeBackground(){if(backgroundUrl)URL.revokeObjectURL(backgroundUrl);backgroundUrl=null;backgroundFileName="";backgroundUpload.value="";Object.assign(backgroundSettings,{visible:true,opacity:1,mode:"fit",x:0,y:0});imageDraggingEnabled=false;backgroundDrag=null;resetToDefaultCanvas();updateEndpointInputs();updateBackgroundVisuals();updateBackgroundControls();update()}
function toggleBackgroundVisibility(){if(!backgroundUrl)return;backgroundSettings.visible=!backgroundSettings.visible;backgroundDrag=null;updateBackgroundVisuals();updateBackgroundControls()}
function updateBackgroundOpacity(e){backgroundSettings.opacity=Number(e.target.value);updateBackgroundVisuals()}
function updateBackgroundMode(e){backgroundSettings.mode=e.target.value;updateBackgroundVisuals()}
function generateCurve(){const curvature=Number(document.getElementById("curvature").value),segments=Number(document.getElementById("segments").value),start=points[0],end=points[points.length-1],next=[{...start}];for(let i=0;i<segments;i++){const t0=i/segments,t1=(i+1)/segments,sx=start.x+(end.x-start.x)*t0,sy=start.y+(end.y-start.y)*t0,ex=start.x+(end.x-start.x)*t1,ey=start.y+(end.y-start.y)*t1,dx=ex-sx,dy=ey-sy,dist=Math.hypot(dx,dy)||1,dir=i%2===0?1:-1,mx=(sx+ex)/2,my=(sy+ey)/2,nx=(-dy/dist)*dir,ny=(dx/dist)*dir,h=dist*curvature,cx=mx+nx*h,cy=my+ny*h;next.push({x:sx+(cx-sx)*.6,y:sy+(cy-sy)*.6},{x:ex+(cx-ex)*.6,y:ey+(cy-ey)*.6},{x:ex,y:ey})}points=next;updateEndpointInputs();update()}
function preview(){gsap.killTweensOf(box);gsap.set(box,{x:points[0].x,y:points[0].y,scale:1});gsap.to(box,{duration:2,ease:"power2.inOut",motionPath:{path:buildPath(),type:"cubic"},onUpdate(){gsap.set(box,{scale:1+.5*Math.sin(Math.PI*this.progress())})}})}
svg.addEventListener("mousedown",onPointerDown);svg.addEventListener("mousemove",onPointerMove);window.addEventListener("mouseup",onPointerUp);window.addEventListener("resize",update);pointsTableBody.addEventListener("input",e=>{const input=e.target;if(!input.matches("input[data-point-index]"))return;const i=Number(input.dataset.pointIndex),v=Number(input.value);if(!Number.isFinite(v))return;points[i][input.dataset.axis]=clamp(v,0,getCanvasSize()[input.dataset.axis==="x"?"width":"height"]);update()});
document.getElementById("generate").addEventListener("click",generateCurve);document.getElementById("addSegment").addEventListener("click",addSegment);document.getElementById("removeSegment").addEventListener("click",removeSegment);document.getElementById("snap").addEventListener("click",toggleSnap);document.getElementById("preview").addEventListener("click",preview);document.getElementById("applyEndpoints").addEventListener("click",applyEndpoints);document.getElementById("swapEndpoints").addEventListener("click",swapStartEnd);document.getElementById("lockEndpoints").addEventListener("click",toggleLockEndpoints);backgroundUpload.addEventListener("change",handleBackgroundUpload);clearBackground.addEventListener("click",removeBackground);toggleBackground.addEventListener("click",toggleBackgroundVisibility);toggleImageDragging.addEventListener("click",toggleImageDraggingMode);backgroundOpacity.addEventListener("input",updateBackgroundOpacity);backgroundMode.addEventListener("change",updateBackgroundMode);
resetToDefaultCanvas();updateBackgroundVisuals();updateBackgroundControls();updateEndpointInputs();update();
